[Link del Repositorio de Github de la Tarea 10 - Joel Quilumba](https://github.com/iamjoel01/tarea10_metodos_numericos)

‎   
‎   
‎   
‎   
‎   
‎   
‎   
‎   

‎   
‎   
‎   
‎   
‎   


# CONJUNTO DE EJERCICIOS

## Pregunta 1
**Realice las siguientes multiplicaciones matriz-matriz:**

In [2]:
def multiply_matrices(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Número de columnas de A debe ser igual al número de filas de B")
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result


a.
$$
\begin{pmatrix}
2 & -3 \\
3 & -1
\end{pmatrix}
$$
$$
\begin{pmatrix}
1 & 5 \\
2 & 0
\end{pmatrix}
$$

In [4]:
A1 = [
    [2, -3],
    [3, -1]
]

B1 = [
    [1, 5],
    [2, 0]
]
result1 = multiply_matrices(A1, B1)
print("Resultado de a:")
for fila in result1:
    print(fila)

Resultado de a:
[-4, 10]
[1, 15]


b.
$$
\begin{pmatrix}
2 & -3 \\
3 & -1
\end{pmatrix}
$$
$$
\begin{pmatrix}
1 & 5 & -4 \\
-3 & 2 & 0
\end{pmatrix}
$$


In [6]:
A2 = [
    [2, -3],
    [3, -1]
]

B2 = [
    [1, 5, -4],
    [-3, 2, 0]
]
result2 = multiply_matrices(A2, B2)
print("\nResultado de b:")
for fila in result2:
    print(fila)


Resultado de b:
[11, 4, -8]
[6, 13, -12]


c. 
$$
\begin{pmatrix}
2 & -3 & 1 \\
4 & 3 & 0 \\
5 & 2 & -4
\end{pmatrix}
$$
$$
\begin{pmatrix}
0 & 1 & -2 \\
1 & 0 & -1 \\
2 & 3 & -2
\end{pmatrix}
$$

In [ ]:
A3 = [
    [2, -3, 1],
    [4, 3, 0],
    [5, 2, -4]
]

B3 = [
    [0, 1, -2],
    [1, 0, -1],
    [2, 3, -2]
]


d. 
$$
\begin{pmatrix}
2 & 1 & 2 \\
-2 & 3 & 0 \\
2 & -1 & 3
\end{pmatrix}
$$
$$
\begin{pmatrix}
1 & -2 \\
-4 & 1 \\
0 & 2
\end{pmatrix}
$$

In [3]:
A4 = [
    [2, 1, 2],
    [-2, 3, 0],
    [2, -1, 3]
]

B4 = [
    [1, -2],
    [-4, 1],
    [0, 2]
]
result4 = multiply_matrices(A4, B4)
print("\nResultado de d:")
for fila in result4:
    print(fila)


Resultado de d:
[-2, 1]
[-14, 7]
[6, 1]


## Pregunta 2
**Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:**

a.
$$
\begin{pmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{pmatrix}
$$

In [6]:
import numpy as np

A = np.array([
    [4, 2, 6],
    [3, 0, 7],
    [-2, -1, -3]
])

det_A = np.linalg.det(A)
if det_A != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = None

print(f"Matriz A:")
print(f"  Determinante: {det_A}")
if inv_A is not None:
    print(f"  Inversa:\n{inv_A}\n")
else:
    print("  La matriz es singular y no tiene inversa.\n")


Matriz A:
  Determinante: 0.0
  La matriz es singular y no tiene inversa.



b.
$$
\begin{pmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1
\end{pmatrix}
$$

In [7]:
import numpy as np

B = np.array([
    [1, 2, 0],
    [2, 1, -1],
    [3, 1, 1]
])

det_B = np.linalg.det(B)
if det_B != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = None

print(f"Matriz B:")
print(f"  Determinante: {det_B}")
if inv_B is not None:
    print(f"  Inversa:\n{inv_B}\n")
else:
    print("  La matriz es singular y no tiene inversa.\n")


Matriz B:
  Determinante: -8.000000000000002
  Inversa:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]



c.
$$
\begin{pmatrix}
1 & 1 & -1 & 1 \\
1 & 2 & -4 & -2 \\
2 & 1 & 1 & 5 \\
-1 & 0 & -1 & -4
\end{pmatrix}
$$



In [8]:
import numpy as np

C = np.array([
    [1, 1, -1, 1],
    [1, 2, -4, -2],
    [2, 1, 1, 5],
    [-1, 0, -2, -4]
])

det_C = np.linalg.det(C)
if det_C != 0:
    inv_C = np.linalg.inv(C)
else:
    inv_C = None

print(f"Matriz C:")
print(f"  Determinante: {det_C}")
if inv_C is not None:
    print(f"  Inversa:\n{inv_C}\n")
else:
    print("  La matriz es singular y no tiene inversa.\n")


Matriz C:
  Determinante: 0.0
  La matriz es singular y no tiene inversa.



c.
$$
\begin{pmatrix}
4 & 0 & 0 & 0 \\
6 & 7 & 0 & 0 \\
9 & 11 & 1 & 0 \\
5 & 4 & 1 & 1
\end{pmatrix}
$$



In [9]:
import numpy as np

D = np.array([
    [4, 0, 0, 0],
    [6, 7, 0, 0],
    [9, 11, 1, 0],
    [5, 4, 1, 1]
])

det_D = np.linalg.det(D)
if det_D != 0:
    inv_D = np.linalg.inv(D)
else:
    inv_D = None

print(f"Matriz D:")
print(f"  Determinante: {det_D}")
if inv_D is not None:
    print(f"  Inversa:\n{inv_D}\n")
else:
    print("  La matriz es singular y no tiene inversa.\n")


Matriz D:
  Determinante: 28.00000000000001
  Inversa:
[[ 2.50000000e-01 -2.46716228e-17  0.00000000e+00  0.00000000e+00]
 [-2.14285714e-01  1.42857143e-01 -0.00000000e+00 -0.00000000e+00]
 [ 1.07142857e-01 -1.57142857e+00  1.00000000e+00 -0.00000000e+00]
 [-5.00000000e-01  1.00000000e+00 -1.00000000e+00  1.00000000e+00]]



## Pregunta 3
**Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:**

In [11]:
import numpy as np

A = np.array([
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

b1 = np.array([6, 4, -2, 5])
b2 = np.array([1, 1, 2, -1])

a. $x_{1}-x_{2}+2x_{3}-x_{4}=6$  
$x_{1}‎ ‎ ‎ -x_{3}+x_{4}=4$   
$2x_{1}+x_{2}-3x_{3}-4x_{4}=-2$  
$‎ ‎ ‎ ‎ -x_{2}+x_{3}-x_{4}=5$

In [13]:
x1 = np.linalg.solve(A, b1)
print("Solución del primer sistema (x1, x2, x3, x4):")
print(x1)

Solución del primer sistema (x1, x2, x3, x4):
[ 3. -6. -2. -1.]


b. $x_{1}-x_{2}+2x_{3}-x_{4}=1$  
$x_{1}‎ ‎ ‎ -x_{3}+x_{4}=1$   
$2x_{1}+x_{2}-3x_{3}-4x_{4}=2$  
$‎ ‎ ‎ ‎ -x_{2}+x_{3}-x_{4}=1$

In [15]:
x2 = np.linalg.solve(A, b2)
print("\nSolución del segundo sistema (x1, x2, x3, x4):")
print(x2)


Solución del segundo sistema (x1, x2, x3, x4):
[1. 1. 1. 1.]


## Pregunta 4
**Encuentre los valores de A que hacen que la siguiente matriz sea singular**

$$A=$$ $$
\begin{pmatrix}
1 & -1 & a \\
2 & 2 & 1 \\
0 & a & -3/2
\end{pmatrix}
$$

In [16]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()
alpha_solutions = sp.solve(det_A, alpha)
print("Valores de alpha que hacen que la matriz A sea singular:")
print(alpha_solutions)

Valores de alpha que hacen que la matriz A sea singular:
[-1.50000000000000, 2.00000000000000]


## Pregunta 5
**Resuelva los siguientes sistemas lineales:**

![](ma1.jpg)

In [19]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve

A1 = np.array([[1, 0, 0], [2, 1, 0], [-1, 0, 1]])
B1 = np.array([[2, 3, -1], [0, -2, 1], [0, 0, 3]])
C1 = np.array([2, -1, 1])

P1, L1, U1 = lu(A1)
B1_inv = np.linalg.inv(B1)
A1_prime = np.dot(B1_inv, A1)
lu1, piv1 = lu_factor(A1_prime)
x1 = lu_solve((lu1, piv1), C1)

print("Solución del sistema a:")
print(x1)

Solución del sistema a:
[-2.13162821e-16  3.00000000e+00  3.00000000e+00]


![](ma2.jpg)

In [21]:
A2 = np.array([[2, 0, 0], [-1, 1, 0], [3, 2, -1]])
B2 = np.array([[1, 1, 1], [0, 1, 2], [0, 0, 1]])
C2 = np.array([-1, 3, 0])

P2, L2, U2 = lu(A2)
B2_inv = np.linalg.inv(B2)
A2_prime = np.dot(B2_inv, A2)
lu2, piv2 = lu_factor(A2_prime)
x2 = lu_solve((lu2, piv2), C2)

print("Solución del sistema b:")
print(x2)

Solución del sistema b:
[ 1.  4. 11.]


## Pregunta 6
**Factorice las siguientes matrices en la descomposición *LU* mediante el algoritmo de factorización *LU* con $l_{ii} = 1$ para todas las $i$**

a.
$$
\begin{pmatrix}
2 & -1 & 1 \\
3 & 3 & 9 \\
3 & 3 & 5
\end{pmatrix}
$$

In [22]:
import numpy as np
from scipy.linalg import lu

a = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
])

P_a, L_a, U_a = lu(a)

print("Factorización LU de la matriz a:")
print("L:")
print(L_a)
print("U:")
print(U_a)
print()


Factorización LU de la matriz a:
L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]



b.
$$
\begin{pmatrix}
1.012 & -2.132 & 3.104 \\
-2.132 & 4.096 & -7.013 \\
3.104 & -7.013 & 0.014
\end{pmatrix}
$$

In [23]:
import numpy as np
from scipy.linalg import lu

b = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
])

P_b, L_b, U_b = lu(b)

print("Factorización LU de la matriz b:")
print("L:")
print(L_b)
print("U:")
print(U_b)
print()


Factorización LU de la matriz b:
L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]



c.
$$
\begin{pmatrix}
2 & 0 & 0 & 0 \\
1 & 1.5 & 0 & 0 \\
0 & -3 & 0.5 & 0 \\
2 & -2 & 1 & 1
\end{pmatrix}
$$



In [24]:
import numpy as np
from scipy.linalg import lu

c = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
])

P_c, L_c, U_c = lu(c)

print("Factorización LU de la matriz c:")
print("L:")
print(L_c)
print("U:")
print(U_c)
print()


Factorización LU de la matriz c:
L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]



d.
$$
\begin{pmatrix}
2.1756 & 4.0231 & -2.1732 & 5.1967 \\
-4.0231 & 6.0000 & 0 & 1.1973 \\
-1.0000 & -5.2107 & 1.1111 & 0 \\
6.0235 & 7.0000 & 0 & -4.1561
\end{pmatrix}
$$



In [25]:
import numpy as np
from scipy.linalg import lu

d = np.array([
    [2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6, 0, 1.1973],
    [-1, -5.2107, 1.1111, 0],
    [6.0235, 7, 0, -4.1561]
])

P_d, L_d, U_d = lu(d)

print("Factorización LU de la matriz d:")
print("L:")
print(L_d)
print("U:")
print(U_d)
print()


Factorización LU de la matriz d:
L:
[[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.36118536  0.14002434  1.          0.        ]
 [-0.16601644 -0.37924771 -0.5112737   1.        ]]
U:
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.         -2.1732      6.91885959]
 [ 0.          0.          0.          2.24878393]]



## Pregunta 7
**Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.**

a. $2x_{1}-x_{2}+x_{3}=1$  
$3x_{1}‎+3x_{2}+9x_{3}=0$   
$3x_{1}+3x_{2}+5x_{3}=4$  

In [26]:
import numpy as np

def lu_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = np.copy(A)
    
    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            U[j, i:] -= factor * U[i, i:]
            L[j, i] = factor
    
    return L, U

def solve_lu(L, U, b):
    y = np.zeros_like(b, dtype=np.double)
    for i in range(len(b)):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    x = np.zeros_like(b, dtype=np.double)
    for i in range(len(b) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

# Sistema a
A_a = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]])
b_a = np.array([-1, 0, 4])

L_a, U_a = lu_decomposition(A_a)
x_a = solve_lu(L_a, U_a, b_a)

print(f"Solución del sistema a: {x_a}")


Solución del sistema a: [ 1.  2. -1.]


b. $1.012x_{1}-2.132x_{2}+3.104x_{3}=1.984$  
$-2.132x_{1}‎+4.096x_{2}-7.013x_{3}=-5.049$   
$3.104x_{1}-7.013x_{2}+0.014x_{3}=-3.895$  

In [27]:
import numpy as np

# Funciones lu_decomposition y solve_lu definidas previamente

# Sistema b
A_b = np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]])
b_b = np.array([1.984, -5.049, -3.895])

L_b, U_b = lu_decomposition(A_b)
x_b = solve_lu(L_b, U_b, b_b)

print(f"Solución del sistema b: {x_b}")


Solución del sistema b: [1. 1. 1.]


c. $2x_{1}‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ =3$   
$x_{1}+1.5‎x_{2} ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ =4.5$   
$‎ ‎ ‎ ‎ ‎ ‎ -3x_{2}+0.5x_{3}‎ ‎ =-6.6$  
$2x_{1}-2x_{2}+x_{3}+x_{4}=0.8$ 

In [28]:
import numpy as np

# Funciones lu_decomposition y solve_lu definidas previamente

# Sistema c
A_c = np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]])
b_c = np.array([3, 4.5, -6.6, 0.8])

L_c, U_c = lu_decomposition(A_c)
x_c = solve_lu(L_c, U_c, b_c)

print(f"Solución del sistema c: {x_c}")


Solución del sistema c: [ 1.5  2.  -1.2  3. ]


d. $2.1756x_{1}+4.0231x_{2}-2.1732x_{3}+5.1967x_{4}=17.102$  
$-4.0231x_{1}‎+6.0000x_{2}‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ +1.1973x_{4}=-6.1593$   
$-1.0000x_{1}‎-5.2107x_{2}+1.1111x_{3}‎ ‎ ‎ ‎ ‎ ‎ ‎ =3.0004$   
$6.0235x_{1}‎+7.0000x_{2} ‎ ‎ ‎ ‎ ‎ ‎ ‎ -4.1561x_{4}=0.0000$   

In [30]:
import numpy as np

# Funciones lu_decomposition y solve_lu definidas previamente

# Sistema d
A_d = np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6, 0, 1.1973], [-1, -5.2107, 1.1111, 0], [6.0235, 7, 0, -4.1561]])
b_d = np.array([17.102, -6.1593, 3.0004, 0])

L_d, U_d = lu_decomposition(A_d)
x_d = solve_lu(L_d, U_d, b_d)

print(f"Solución del sistema d: {x_d}")


Solución del sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]


[Link del Repositorio de Github de la Tarea 10 - Joel Quilumba](https://github.com/iamjoel01/tarea10_metodos_numericos)